### ISSUE TITLE
能否开个java版的？

### ISSUE THREAD

**Issue by magic0908** [yjfnypeu/EasyAndroid#2]
首先感谢作者开源，我觉得很多代码思路有参考价值，
但是我目前还是在用java写代码，没系统学过kt，看代码有点费劲，能否开个java版的

**Comment by yjfnypeu** [comment]
用的话，kt直接支持java。你使用java编写也是可以直接使用的

**Comment by magic0908** [comment]
我知道是可以直接用的，我意思是想看看代码的实现过程，但是kt语法我不太了解。
如果你确实觉得没必要的话也没事的

**Comment by yjfnypeu** [comment]
嗯，其实kt语法很容易理解。而且看思路的话其实不懂kt直接看我觉得也能大致理解。如果过程中有哪个地方不清楚的。也可以加群到群里问。我就不单独再提供java版的了
