### ISSUE TITLE
java不能调用imagegetter

### ISSUE THREAD

**Issue by RiceRichhonour** [yjfnypeu/EasyAndroid#6]
EasyImageGetter.create()
                            .setPlaceHolder(R.drawable.placeholder)// 设置在进行图片加载时的占位图
                            .setError(R.drawable.error)// 设置在进行图片加载失败时的占位图
                            .loadHtml(html, textView)；
这样设置，create方法爆红，没有找到

**Comment by yjfnypeu** [comment]
使用EasyImageGetter.Companion.create()就行。
